name: issue_comment
run-name: issue_comment
on: [issue_comment]
jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: render event details
        run: echo '${{ toJSON(github.event) }}'
