name: events demo 1
on:
  pull_request:
    types:
      - opened
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: output event data
        run: echo '${{ toJSON(github.event) }}'
      - name: Use Code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Linter
        run: npm run lint
      - name: Vitest
        run: npm run test
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: deploy
        run: echo 'Deploying...'
